### ISSUE TITLE
打包运行问题

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [guanxiaohe2017/springBoot-druid-mybatisPlus#1]
是否有运行打包，这怎么运行有三个包 打包mian中的 运行不起来
其他两个可单独运行

**Comment by guanxiaohe2017** [comment]
直接在springBoot-druid-mybatisPlus目录下 执行 mvn clean install












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guanxiaohe2017/springBoot-druid-mybatisPlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午3:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[guanxiaohe2017/springBoot-druid-mybatisPlus] 打包运行问题 (#1)





 
是否有运行打包，这怎么运行有三个包 打包mian中的 运行不起来
 其他两个可单独运行

**Comment by Tuzhiqiang1996** [comment]
![Snipaste_2021-05-25_16-43-33](https://user-images.githubusercontent.com/57666259/119467801-6ef1d600-bd78-11eb-8cfe-97dd2c0ffa56.png)
还是报错！

**Comment by guanxiaohe2017** [comment]
估计是maven有问题吧 你reimport以下呢 不行的话改下maven配置 这是我的配置文件






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guanxiaohe2017/springBoot-druid-mybatisPlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guanxiaohe2017/springBoot-druid-mybatisPlus] 打包运行问题 (#1)





 

 还是报错！
